<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  /* dompdf has limited CSS support (no flexbox/grid, patchy object-fit), so
     this stays table/box based rather than mirroring the HTML email 1:1. */
  /* DejaVu Sans (bundled with dompdf) is used instead of Helvetica because
     Helvetica's built-in font has no glyph for the Naira sign (₦) and
     silently renders it as "?". */
  body { font-family: 'DejaVu Sans', sans-serif; color: #0b1e33; font-size: 12px; margin: 0; }
  .header { background-color: #0b1e33; padding: 18px 28px; }
  .header table { width: 100%; }
  .header img { height: 32px; }
  .header .brand { color: #ffffff; font-size: 15px; font-weight: bold; letter-spacing: 0.04em; }
  .content { padding: 24px 28px; }
  .eyebrow { color: #8a9a5b; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.08em; margin: 0 0 4px; }
  h1 { font-size: 18px; margin: 0 0 4px; color: #0b1e33; }
  .subtitle { color: #64748b; font-size: 11px; margin: 0 0 16px; }
  .cylinder { width: 160px; border: 1px solid #e7e2d6; margin-bottom: 16px; }
  table.details { width: 100%; border-collapse: collapse; font-size: 12px; }
  table.details td { padding: 6px 0; border-bottom: 1px solid #eef0f2; color: #334155; }
  table.details td.label { color: #64748b; }
  table.details td.value { text-align: right; font-weight: bold; color: #0b1e33; }
  table.details tr.total td { border-top: 2px solid #0b1e33; border-bottom: none; padding-top: 10px; font-size: 14px; }
  .badge { color: #d9531e; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.04em; }
  .footer { margin-top: 28px; color: #94a3b8; font-size: 10px; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <table>
      <tr>
        <td style="width: 40px;">
          @if($logoDataUri)
            <img src="{{ $logoDataUri }}" alt="Logo">
          @endif
        </td>
        <td class="brand">D'EL-POSSIBILITIES</td>
      </tr>
    </table>
  </div>

  <div class="content">
    <p class="eyebrow">Payment Receipt</p>
    <h1>Order #{{ $order->id }}</h1>
    <p class="subtitle">Paid {{ optional($order->paid_at)->format('j M Y, g:i A') ?? $order->created_at->format('j M Y, g:i A') }}</p>

    @if($cylinderDataUri)
      <img src="{{ $cylinderDataUri }}" alt="Cylinder" class="cylinder">
    @endif

    <table class="details">
      <tr>
        <td class="label">Student</td>
        <td class="value">{{ $order->user->name ?? '—' }}</td>
      </tr>
      <tr>
        <td class="label">Refill size</td>
        <td class="value">{{ rtrim(rtrim(number_format((float) $order->kg, 2), '0'), '.') }} kg</td>
      </tr>
      <tr>
        <td class="label">Price per kg</td>
        <td class="value">&#8358;{{ number_format((float) $order->price_per_kg, 2) }}</td>
      </tr>
      <tr>
        <td class="label">Gas cost</td>
        <td class="value">&#8358;{{ number_format((float) $order->kg * (float) $order->price_per_kg, 2) }}</td>
      </tr>
      @if($order->loyalty_discount_applied)
      <tr>
        <td class="label">Loyalty discount</td>
        <td class="value" style="color: #8a9a5b;">&minus;&#8358;{{ number_format((float) $order->loyalty_discount_amount, 2) }}</td>
      </tr>
      @endif
      <tr>
        <td class="label">Delivery fee</td>
        <td class="value">&#8358;{{ number_format((float) $order->delivery_fee, 2) }}</td>
      </tr>
      <tr class="total">
        <td class="label" style="font-weight: bold; color: #0b1e33;">Total paid</td>
        <td class="value">&#8358;{{ number_format((float) $order->total_amount, 2) }}</td>
      </tr>
    </table>

    <table class="details" style="margin-top: 14px;">
      <tr>
        <td class="label">Delivery address</td>
        <td class="value" style="font-weight: normal;">
          {{ $order->hostel_address }}
          @if($order->location_type === 'off_campus')
            <br><span class="badge">Off-campus delivery</span>
          @endif
        </td>
      </tr>
      @if($order->paystack_reference)
      <tr>
        <td class="label">Payment reference</td>
        <td class="value" style="font-weight: normal;">{{ $order->paystack_reference }}</td>
      </tr>
      @endif
    </table>

    <p class="footer">Generated by D'EL-Possibilities — thank you for your order.</p>
  </div>
</body>
</html>
